### ISSUE TITLE
The mod ignores ResearchProjectDef.CanStartNow check

### ISSUE THREAD

**Issue by Taranchuk** [catgirlfighter/RimWorld_ResearchWhatever#2]
I believe the mod should check for ResearchProjectDef.CanStartNow in order to pick research projects. Basically it's where the game access to decide if the project is locked or not. Additionaly some mods patch that property in order to lock their research projects. If the mod doesn't check ResearchProjectDef.CanStartNow, then such mods won't work with the mod.

**Comment by catgirlfighter** [comment]
Nice find.
As I CAN remember that method didn't exist when I was working on the mod. Or maybe I'm just blind.
Made a use of it.
